In [1]:
import numpy as np
a=np.array([1.3,5,7])
print(a)

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy


ModuleNotFoundError: No module named 'numpy'

In [3]:
C:\Users\hp\>pip install numpy

SyntaxError: unexpected character after line continuation character (3545464710.py, line 1)

CREATING ARRAYS


In [8]:
import numpy
import numpy as np
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


DIMENSION OF ARRAY


In [9]:
print(a.ndim)

1


In [12]:
c=np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(c.ndim)
print(c)

2
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [14]:
d=np.array([[[1,3,5],[2,4,6],[1,2,3]]])
print(d.ndim)
print(d)

3
[[[1 3 5]
  [2 4 6]
  [1 2 3]]]


ACCESSING ELEMENTS OF ARRAYS


In [15]:
arr=np.array([2,4,6,8])
print(arr[2])

6


In [18]:
A=np.array([[1,3,5],[2,4,6]])
print(A[1,2])
print(A[0,1])
print(A[0,2])
print(A[1,0])


6
3
5
2


In [22]:
arr1=np.array([[[34,51,68],[32,48,64],[30,45,60]]])
print(arr1[0,1])

[32 48 64]


In [23]:
print(A[1,-1])

6


SLICING ARRAY

In [24]:
print(a[1:4])

[3 5 7]


In [25]:
print(a[1:])

[3 5 7 9]


In [26]:
print(arr1[:3])

[[[34 51 68]
  [32 48 64]
  [30 45 60]]]


NEGATIVE INDEXING

In [31]:
print(a[-3:-1])

[5 7]


In [32]:
aRr=np.array([1,2,3,5])
print(aRr[1:5:2])

[2 5]


In [34]:
print(aRr[1:5])

[2 3 5]


In [7]:
import numpy as np
d=np.array([[1,3,4,5,7],[2,4,8,6,9]])
print(d[1,1:4])


[4 8 6]


COPYING ARRAY

In [8]:
import numpy as np
arra=np.array([1,4,7,20])
x=arra.copy()
arra[0]=2
arra[2]=10
print(arra)
print(x)

[ 2  4 10 20]
[ 1  4  7 20]


VIEWING ARRAY

In [9]:
import numpy as np
arr=np.array([2,3,5,7])
x=arr.view()
arr[0]=1
print(arr)
print(x)

[1 3 5 7]
[1 3 5 7]


SHAPE OF ARRAY

In [10]:
import numpy as np
a=np.array([[1,3,5,7],[5,10,15,20]])
print(a.shape)

(2, 4)


RESHAPING AN ARRAY

In [11]:
import numpy as np
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newb=b.reshape(3,4)
print(newb)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
import numpy as np
Arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArr=Arr.reshape(2,3,2)
newArr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
import numpy as np
a=np.array


JOINING TWO ARRAYS

In [1]:
import numpy as np
arr1=np.array([1,3,5])
arr2=np.array([4,8,12])
arr=np.concatenate((arr1,arr2))
arr

array([ 1,  3,  5,  4,  8, 12])

In [2]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a=np.concatenate((a1,a2),axis=1)
print(a)

[[1 2 5 6]
 [3 4 7 8]]


STACKING ALONG ROWS

In [3]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([2,4,6])
a=np.vstack((a1,a2))
print(a)


[[1 2 3]
 [2 4 6]]


SPLITTING ARRAYS

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.array_split(arr,3)#splitting of array in 3 parts
print(newarr)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
newa=np.array_split(a,3)
print(newa[0])
print(newa[1])
print(newa[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [9]:
import numpy as np
a=np.array([[1,22,1],[2,33,2],[3,44,3],[4,55,4],[5,66,5],[6,77,6]])
newa=np.array_split(a,3)
print(newa)
NEWa=np.hsplit(a, 3)
print(NEWa)

[array([[ 1, 22,  1],
       [ 2, 33,  2]]), array([[ 3, 44,  3],
       [ 4, 55,  4]]), array([[ 5, 66,  5],
       [ 6, 77,  6]])]
[array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]]), array([[22],
       [33],
       [44],
       [55],
       [66],
       [77]]), array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])]


SEARCHING ARRAYS

In [11]:
import numpy as np
arR=np.array([1,2,3,4,5,4,4])
x=np.where(arR==4)#gives the array of indices where the value asked is present
print(x)

(array([3, 5, 6], dtype=int64),)


In [14]:
#FINDING THE INDICES WHERE EVEN VALUES ARE PRESENT
import numpy as np
a=np.array=([1,2,3,4,5,6,7,8,9,10])
x=np.where(a==2 or a==4 or a==6 or a==8 or a==10)
print(x)

(array([], dtype=int64),)


C:\Users\hp\AppData\Local\Temp\ipykernel_2412\4049766418.py:4: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  x=np.where(a==2 or a==4 or a==6 or a==8 or a==10)


RANDOM

In [21]:
import numpy as np
from numpy import random
x=random.randint(10)
print(x)

TypeError: 'list' object is not callable

In [20]:
from numpy import random
x=random.rand()
print(x)

0.1677937263865854


In [1]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[80 72 23 46 78]


In [2]:
from numpy import random
x=random.randint(100, size=(3,5))
print(x)

[[57 38 12 32  6]
 [64 74 94  2 33]
 [47 21 77 24 54]]


In [3]:
from numpy import random
x=random.rand(3, 5)
print(x)

[[0.18092246 0.32921352 0.70310216 0.07918959 0.55108507]
 [0.72866551 0.50882353 0.91608687 0.87764491 0.93542256]
 [0.04481046 0.37338805 0.0983387  0.07015011 0.23627305]]


In [4]:
from numpy import random
x=random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(100))
print(x)

[7 7 5 7 3 5 5 7 5 5 7 7 7 5 7 5 5 5 5 7 7 7 5 7 5 7 7 5 7 7 3 7 5 5 7 3 5
 5 7 7 7 5 7 5 7 7 7 7 3 3 7 7 3 7 7 5 7 7 3 7 5 5 3 7 5 7 5 3 7 7 5 5 7 3
 7 7 7 5 7 7 7 3 7 5 5 5 5 7 3 5 7 5 5 7 5 7 7 7 7 7]


In [5]:
from numpy import random
x=random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size=(3,5))
print(x)

[[5 5 7 7 7]
 [3 5 5 7 5]
 [7 7 7 7 5]]


SHUFFLING

In [6]:
from numpy import random
import numpy as np
arr=np.array([1,2,3,4,5])
random.shuffle(arr) #changes the original array too
print(arr)

[2 1 5 4 3]


GENERATION OF PERMUTATION OF ARRAYS

In [7]:
from numpy import random
import numpy as np
a=np.array([1,2,3,4,5])
print(random.permutation(a)) #permutation() methods give a rearranged array but doesnot change the original array

[4 1 2 3 5]


OPERATIONS ON MATRICES USING NUMPY

In [8]:
a=np.array([11,22,33,44,55,66]).reshape(2,3)
b=np.array([22,44,66,88,110,132]).reshape(2,3)
print(a)
print(b)
print("Element-wise addition:")
c=a+b
print(c)
print("element-wise subtraction:")
s=a-b
print(s)
print("Element-wise multiplication:")
m=a*b
print(m)

[[11 22 33]
 [44 55 66]]
[[ 22  44  66]
 [ 88 110 132]]
Element-wise addition:
[[ 33  66  99]
 [132 165 198]]
element-wise subtraction:
[[-11 -22 -33]
 [-44 -55 -66]]
Element-wise multiplication:
[[ 242  968 2178]
 [3872 6050 8712]]


MATRIX MULTIPLICATION ----dot product

In [9]:
a=np.array([1,2,3,4,5,6]).reshape(2,3)
b=np.array([2,4,6,8,10,12]).reshape(3,2)
print(a)
print(b)
print(a@b) #or np.dot(a, b)

[[1 2 3]
 [4 5 6]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 44  56]
 [ 98 128]]


In [10]:
#TRANSPOSE OF MATRIX
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


STATISTICAL OPERATIONS

In [11]:
print(a.sum()) #adds all items
print(a.sum(axis=1)) #row-wise sum
print(a.sum(axis=0)) #cl wise sum


21
[ 6 15]
[5 7 9]


In [12]:
print(a.mean())
print(a.mean(axis=1))
print(a.mean(axis=0))

3.5
[2. 5.]
[2.5 3.5 4.5]


In [14]:
print(b.max())
print(a.min())
print(a.max(axis=1))
print(a.min(axis=0))

12
1
[3 6]
[1 2 3]


SLICING

In [19]:
x=np.array(10,int).reshape(10, 10).astype(int)
print(x)

ValueError: cannot reshape array of size 1 into shape (10,10)

In [20]:
#3rd row
print(x[2])
#last row
print(x[-1])
#first column
print(x[:, 0])
#last column
print(x[:, -1])
#last 3 columns
print(x[:, -3:])
#first three cols
print(x[:, :3])

[7 7 7 7 5]
[7 7 7 7 5]
[5 3 7]
[7 5 5]
[[7 7 7]
 [5 7 5]
 [7 7 5]]
[[5 5 7]
 [3 5 5]
 [7 7 7]]
